# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-25 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobmge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jposition', models.CharField(max_length=20)),
                ('jplace', models.CharField(max_length=20)),
                ('jwages', models.IntegerField()),
                ('jcount', models.CharField(max_length=20)),
                ('jskill', models.CharField(max_length=100)),
                ('mgetype', models.CharField(max_length=20)),
                ('epname', models.CharField(max_length=20)),
                ('epcontent', models.CharField(max_length=100)),
                ('boon', models.CharField(max_length=20)),
                ('settime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='leavemge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=20)),
                ('epname', models.CharField(max_length=20)),
                ('substance', models.CharField(max_length=100)),
                ('isenter', models.IntegerField()),
            ],
        ),


        migrations.CreateModel(
            name='wkaddrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addrs', models.CharField(max_length=50)),
                ('isdel', models.CharField(max_length=50)),
            ],
        ),
    ]
