# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-01 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('cplace', models.CharField(max_length=20)),
                ('ctel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='hangye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='jobmge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jposition', models.CharField(max_length=20)),
                ('jplace', models.CharField(max_length=20)),
                ('jwages', models.IntegerField()),
                ('jcount', models.CharField(max_length=20)),
                ('jskill', models.CharField(max_length=100)),
                ('mgetype', models.CharField(max_length=20)),
                ('epname', models.CharField(max_length=20)),
                ('epcontent', models.CharField(max_length=100)),
                ('boon', models.CharField(max_length=20)),
                ('settime', models.DateTimeField()),
                ('ccompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OJob.company')),
            ],
        ),
        migrations.CreateModel(
            name='leavemge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=20)),
                ('epname', models.CharField(max_length=20)),
                ('substance', models.CharField(max_length=100)),
                ('isenter', models.IntegerField()),
                ('ccompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OJob.company')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('upasswd', models.CharField(max_length=20)),
                ('upower', models.IntegerField()),
                ('uaddress', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('ucount', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='usernote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=20)),
                ('usex', models.CharField(max_length=20)),
                ('uage', models.IntegerField()),
                ('exp', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
                ('goalseat', models.CharField(max_length=50)),
                ('edubg', models.CharField(max_length=50)),
                ('evaluation', models.CharField(max_length=100)),
                ('uuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OJob.user')),
            ],
        ),
        migrations.CreateModel(
            name='wkaddrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addrs', models.CharField(max_length=50)),
                ('isdel', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='reply',
            name='uuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OJob.user'),
        ),
        migrations.AddField(
            model_name='leavemge',
            name='uuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OJob.user'),
        ),
    ]
