# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-01 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(default='0', max_length=20, unique=True)),
                ('cplace', models.CharField(default='0', max_length=20)),
                ('ctel', models.CharField(default='0', max_length=20)),
                ('createid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='jobmge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jposition', models.CharField(max_length=20)),
                ('jplace', models.CharField(default='0', max_length=20)),
                ('jwages', models.IntegerField(default=0)),
                ('jcount', models.CharField(default='0', max_length=20)),
                ('jskill', models.CharField(default='0', max_length=100)),
                ('workexp', models.CharField(default='0', max_length=100)),
                ('epid', models.IntegerField(default=0)),
                ('epname', models.CharField(default='0', max_length=20)),
                ('settime', models.DateTimeField()),
                ('isenter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='leavemge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default='0', max_length=20)),
                ('title', models.CharField(default='0', max_length=20)),
                ('content', models.CharField(default='0', max_length=20)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default='0', max_length=20)),
                ('epname', models.CharField(default='0', max_length=20)),
                ('jposition', models.CharField(default='0', max_length=20)),
                ('substance', models.CharField(default='无', max_length=100)),
                ('isenter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, unique=True)),
                ('upasswd', models.CharField(max_length=20)),
                ('upower', models.IntegerField(default=1)),
                ('uaddress', models.CharField(default='0', max_length=20)),
                ('telephone', models.CharField(default='0', max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='usernote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, unique=True)),
                ('realname', models.CharField(max_length=20)),
                ('usex', models.CharField(max_length=20)),
                ('uage', models.IntegerField(default=0)),
                ('exp', models.CharField(max_length=100)),
                ('telephone', models.CharField(default='0', max_length=20)),
                ('language', models.CharField(default='0', max_length=20)),
                ('edubg', models.CharField(default='0', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='wkaddrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addrs', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('isdel', models.CharField(max_length=50)),
            ],
        ),
    ]
