# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-28 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJob', '0002_hangye'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('upasswd', models.CharField(max_length=20)),
                ('upower', models.IntegerField()),
                ('uaddress', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('ucount', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='usernote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=20)),
                ('usex', models.CharField(max_length=20)),
                ('uage', models.IntegerField()),
                ('exp', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
                ('goalseat', models.CharField(max_length=50)),
                ('edubg', models.CharField(max_length=50)),
                ('evaluation', models.CharField(max_length=100)),
            ],
        ),
    ]
